version: '3'
services:

  flask:
    image: mamad-flask:test1
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile

  #nginx:
  #  image: mamad-nginx:rc1.1
  #  build:
  #    context: .
  #    dockerfile: ./docker/nginx/Dockerfile