version: '3'
services:
  flask:
    image: mamad-flask:rc2
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    ports:
    - "80:80"
  nginx:
    image: mamad-nginx:rc1.1
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
    - "80:80"