apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-configmap
data:
  default.conf: |
    server {
       listen       8080;
       server_name  localhost;
       location / {
           proxy_pass  http://localhost:5000/;
        }
      }