apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |-
    server {
      listen 6000;
      server_name nginx;

      location / {
          proxy_pass http://localhost:5000/;
      }
    }