apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.metaName }}
  labels:
    app: {{ .Values.deployment.appName }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.appName }}
    spec:
      containers:
        - name: {{ .Values.deployment.appName }}
          image: {{ .Values.deployment.image.name }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
          resources:
            requests:
              memory: {{ .Values.deployment.resources.requests.memory }}
              cpu: {{ .Values.deployment.resources.requests.cpu }}
            limits:
              memory: {{ .Values.deployment.resources.limits.memory }}
              cpu: {{ .Values.deployment.resources.limits.cpu }}
              
        ## sidecar container      
        - name: {{ .Values.sideCar.appName }}
          image: {{ .Values.sideCar.image }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.sideCar.containerPort }}
          resources:
            requests:
              memory: {{ .Values.sideCar.resources.requests.memory }}
              cpu: {{ .Values.sideCar.resources.requests.cpu }}
            limits:
              memory: {{ .Values.sideCar.resources.limits.memory }}
              cpu: {{ .Values.sideCar.resources.limits.cpu }}
          volumeMounts:
            - name: {{ .Values.sideCar.volumeMount.name }}
              mountPath: {{ .Values.sideCar.volumeMount.mountPath }}
              readOnly: {{ .Values.sideCar.volumeMount.readOnly }}

      volumes:
        - name: {{ .Values.sideCar.volume.name }}
          configMap:
            name:  {{ .Values.sideCar.volume.configMapName }}