apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.metaName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deployment.appName }}
  ports:
  - port: {{ .Values.service.svcPort }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}