apiVersion: v1
kind: Service
metadata:
  name: {{ .values.service.meta_name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .values.deployment.app_name }}
  ports:
  - port: {{ .values.service.svc_port }}
    protocol: TCP
    targetPort: {{ .values.service.target_port }}