# Deployment Values
deployment:
  appName: app
  metaName: app-deployment
  replicaCount: 1
  containerPort: 5000
  image:
    name: nginx
    repository: nginx
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "128Mi"
      cpu: "500m"
    limits:
      memory: "256Mi"
      cpu: "1"
  
# Service Values
service:
  type: ClusterIP
  svcPort: 8080
  targetPort: 8080
  metaName: app-svc

# Ingress Values
ingress:
  metaName: app-ingress
  host: chart-example.local
  path: /tree

# config and secret
secret:
  name: flask-config-prod
